### ISSUE TITLE
#49 [STYLE] 메인홈 - 반응형 반영, 레이아웃 수정

### ISSUE THREAD

**Issue by parangwave** [beezSSG/finalproject_pickme_front#128]
## 📢 이슈 내용
메인화면 반응형 반영 및 레이아웃 수정

## 📃 상세 내용
- 메인화면 반응형 반영
- 레이아웃 수정
- 로그인 반영

## ✔ 체크리스트
- [x] 로그인 반영(픽박스 visibility 제어)  https://github.com/beezSSG/finalproject_pickme_front/issues/294#issue-2243079570
- [x] 창업안내, 고객센터 row 삭제 https://github.com/beezSSG/finalproject_pickme_front/issues/294#issue-2243079570
- [x] 픽박스 레이아웃 https://github.com/beezSSG/finalproject_pickme_front/issues/294#issue-2243079570
- [x] 픽박스 반응형
- [x] 픽박스 d-day 데이터 처리
- [x] 픽박스 빈 값 처리
- [x] 사용자 근처 매장 지도; 사용자 위치 허용하지 않았을 시 fallback 처리
- [x] 사용자 근처 매장 지도; 카테고리 checkbox 보여주기
- [x] 사용자 근처 매장 지도; 제일 가까운 매장 하나만 보여주기
        https://github.com/beezSSG/finalproject_pickme_front/issues/294#issue-2243079570
- [x] 사용자 근처 매장 지도; 반응형 
- [x] 사용자 근처 매장 지도; 카테고리 style 수정
- [x] 상품찾기 상품 카테고리 아이콘 애니메이션 https://github.com/beezSSG/finalproject_pickme_front/issues/96#issue-2209811862
- [x] 상품찾기 검색 BE 연결 https://github.com/beezSSG/finalproject_pickme_front/issues/355#issue-2249740349
- [x] 이달의 행사상품 전반적인 style 수정
- [x] 이달의 행사상품 BE 연결 https://github.com/beezSSG/finalproject_pickme_back/issues/191#issue-2249617637
- [x] 이벤트 란 위치 옮기기 https://github.com/beezSSG/finalproject_pickme_front/issues/294#issue-2243079570
- [x] 더보기 버튼들 링크 연결
- [x] navbar 텍스트 색 수정
